### ISSUE TITLE
As a traffic analyist, I would like to see online the new analytics web-application

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/mobility-analytics#14]
Davide Montesin is working on the development of new functionalities. Some of them have been implemented and are available in the correspondent repository. The application should be put in production so that these intermediate modifications are visible (e.g. possibility to see data in case of multiple stations in the same point).

**Comment by rcavaliere** [comment]
@bertolla, can you put in the testing environment the new pull request of Davide concerning some improvements in the Bluetooth elaboration chain?

**Comment by rcavaliere** [comment]
By the way: I have also made a commit of the new analytics with an improvement of the config file for the visualization of station "states" on the map. Can you also integrate it in the pipeline?

**Comment by bertolla** [comment]
I deployed everything on test, seeing that the error disappeared I also deployed on https://analytics.mobility.bz.it

**Comment by rcavaliere** [comment]
@bertolla, thanks!
I however don't see that my modifications on layers-config.json, see: https://github.com/noi-techpark/mobility-analytics/blob/development/src/main/webapp/layers-config.json. It appears to me that this file is currently only in the development branch. Can you put in the master version, so that we can directly check on https://analytics.mobility.bz.it that new implemented logics work?

**Comment by bertolla** [comment]
Sorry I forgot to merge before deployment. Now it should be working.

**Comment by rcavaliere** [comment]
@bertolla I have checked but I don't understand why I don't see the updates.
For instance, for the meteo stations on the map layer now also the stations in Trentino should have a coloured marker when precipitation is measured, but it's not the case... any case about why it is not working?

**Comment by bertolla** [comment]
Is this https://analytics.mobility.bz.it/layers-config.json the correct file? Have you cleared cache to be sure?

**Comment by rcavaliere** [comment]
@bertolla, no, it is not the actual file! This is one is the most updated one: https://github.com/noi-techpark/mobility-analytics/blob/development/src/main/webapp/layers-config.json (now also in master: https://github.com/noi-techpark/mobility-analytics/blob/master/src/main/webapp/layers-config.json)

**Comment by bertolla** [comment]
Then there must be a problem in deployment, I will check the pipeline

**Comment by bertolla** [comment]
Ok my bad, there is a second pipeline just for the deployment which I forgot to trigger. Maybe this should be automated in this case.
Now it should be ok

**Comment by rcavaliere** [comment]
Yes, I confirm! Now the application is really nicer in the map overview, and immediately gives an insight of what's happening on the roads!
