### ISSUE TITLE
As a user I want to redirect BZAnalytics to https://analytics.opendatahub.bz.it/

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/mobility-analytics#26]

**Comment by bertolla** [comment]
On https://analytics.opendatahub.bz.it/ you can check it. 
Did I understand the userstory correctly because to me it seemed the other way around?

**Comment by Piiit** [comment]
@rcavaliere 
Shouldn't https://analytics.mobility.bz.it/ not fully redirect to  https://analytics.opendatahub.bz.it? I see that in both cases the URL is preserved...

**Comment by rcavaliere** [comment]
@Piiit @bertolla @ohnewein what is the expected behaviour, that we just keep https://analytics.opendatahub.bz.it (redirect to this URL in case one tries to connect to https://analytics.mobility.bz.it/) ?

**Comment by Piiit** [comment]
@rcavaliere This is what I understood so far, but I think the last decision has to be made by @ohnewein

**Comment by bertolla** [comment]
:thinking: I kind of thought that the main objective of this userstory was to show the analytics tool on an opendatahub domain. What is the purpose of the redirect?

**Comment by Piiit** [comment]
@bertolla I think we no longer want to split things from the point of view of external users. That is, a tourism data browser should be called browser.opendatahub.bz.it and analytics.mobility... should become analytics.opendatahub.bz.it. PatrickO told us in a longer discussion, that we just divide APIs, but all graphical tools should be just directly under the domain opendatahub.bz.it. For that, I suggest to cleanup old graphical tools' URLs, and just hard-redirect them to the new opendatahub.bz.it URLs to teach people that this is all just the ODH. 

However, @ohnewein  might give a better explanation here

**Comment by rcavaliere** [comment]
I also agree, the URL analytics.opendatahub.bz.it should be the official name.

**Comment by bertolla** [comment]
OK, I created a redirect.
Try it here https://analytics.mobility.bz.it/

**Comment by Piiit** [comment]
@bertolla Tested and works... I move it to done
