### ISSUE TITLE
Create a test environment with automated deployments

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/mobility-analytics#29]
It will be on https://analytics.opendatahub.testingmachine.eu

**Comment by Piiit** [comment]
It runs at https://analytics.opendatahub.testingmachine.eu/analytics/ for the moment

**Comment by Piiit** [comment]
@rcavaliere @bertolla @davidebz Please test... 

@davidebz @noctho Please change the configuration of this webapp to run in the ROOT (not under `analytics`). Alternatively, I can also install nginx to redirect the artifact. What do you prefer?

All files can be found under `infrastructure`...

**Comment by Piiit** [comment]
I fixed the context now, the application runs inside `/` now.

**Comment by bertolla** [comment]
Even though the app seems to be working it does not provide any data.

**Comment by Piiit** [comment]
@noctho We will investigate this issue, see linked issue above. In the meantime, just ignore this problem until we find a proper solution. We change the expiration time of the access token to 4 hours, so the problem will not be visible easily for users.

**Comment by Piiit** [comment]
@noctho For reference, we have a solution for the expiring token now, lets continue with issue #36 ... Good n8
