### ISSUE TITLE
Logged in users should not be kicked out while they interact with the app

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/mobility-analytics#36]
Renew the token from time to time, or when a user interacts with the application.

See authentication server examples repo's vanilla-spa for details

https://github.com/noi-techpark/authentication-server-examples

**Comment by noctho** [comment]
I have implemented the automatic renewal of the access token according to the example.

To do this, I removed all Keycloak properties from dotenv.js and added them to the keycloak.json file. I also changed the `silentCheckSsoRedirectUri` from `callback.html` to `silent-check-sso.html`. I think @Piiit has to change the server configuration, then it should work.

I opened a PR.
