### ISSUE TITLE
Maps: Some downloads of measurements do not succeed

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/mobility-analytics#38]
For example: TRAFFIC

https://mobility.api.opendatahub.testingmachine.eu/tree/Trafficstation/*/latest?limit=-1&distinct=true&select=tmeasurements,mvalue&where=sactive.eq.true,or(and(mperiod.eq.600,tname.eq.Nr. Equivalent Vehicles))

Use `tname.eq."Nr. Equivalent Vehicles"` instead of `tname.eq.Nr. Equivalent Vehicles`

In this case it will fail nevertheless, because on testing this datatype name does not exist. The non-existence should trigger a GUI timeout as well and remove the spinner after showing the error.

**Comment by Piiit** [comment]
This will be reviewed by @bertolla, when done. Since I am away for 2 months now... Thx

**Comment by noctho** [comment]
I have fixed the broken request and if a download now fails the spinner will be removed.

**Comment by Piiit** [comment]
Perfect, it works
