### ISSUE TITLE
Maps: We have some errors in the console

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/mobility-analytics#39]
![Selection_135](https://user-images.githubusercontent.com/6096063/86102494-e0b79600-babb-11ea-99ae-b85b781ff918.png)

**Comment by Piiit** [comment]
@noctho Please have a look...

**Comment by noctho** [comment]
Can you explain when you get this error? Because I have never noted this type of error in the console ...

**Comment by Piiit** [comment]
@noctho Cannot reproduce it anymore in the new version, maybe it was a local issue
